defmodule Hourglass.WorkerLauncher do
  @moduledoc """
  Boot-time supervisor child that starts the default Elixir Temporal
  worker — the one that polls the `"default"` task queue.

  Lives inside `Hourglass.Subsystem` (`:rest_for_one`) as the
  last child. On a `BridgeHolder` crash, the cascade restarts
  `WorkerRegistry`, `Worker.Supervisor`, then this module — which
  re-invokes `Worker.Supervisor.start_worker/1` and re-establishes the
  default Worker against the fresh subtree. No zombie state.

  Returns `:ignore` from `start_link/0` so no process lingers; the
  Worker's own GenServer (registered under `Worker.Supervisor`)
  carries the runtime state.

  ## Structural dispatch — no module registration

  The default Worker needs only a task queue. Workflow and activity
  modules are resolved purely structurally at dispatch time: the
  Temporal type name on the wire is `Atom.to_string(module)` (e.g.
  `"Elixir.MyApp.Workflows.Hello"`), so the worker recovers the module
  atom via `String.to_existing_atom/1` and verifies it is a loaded
  Hourglass workflow or activity by checking for the
  `__workflow_input_type__/0` / `__activity_input_type__/0` marker
  generated by `use Hourglass.Workflow` / `use Hourglass.Activity`.
  No `config :hourglass, :workflows` / `:activities` lists are needed.

  ## Disabling

  Set `config :hourglass, :start_default_worker, false` to skip
  registration. Tests use this so per-test Workers (started via
  `Worker.Supervisor.start_worker/1` with unique task queues) own
  worker lifecycle without contention from a global default.
  """

  # credo:disable-for-next-line Credo.Check.Readability.AliasAs
  alias Hourglass.Worker.Supervisor, as: WorkerSupervisor

  @default_task_queue "default"

  @spec child_spec(term()) :: Supervisor.child_spec()
  def child_spec(_opts) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, []},
      type: :worker,
      restart: :transient
    }
  end

  @spec start_link() :: :ignore | {:error, term()}
  def start_link do
    if Application.get_env(:hourglass, :start_default_worker, true) do
      launch()
    else
      :ignore
    end
  end

  defp launch do
    # No :namespace opt — BridgeHolder.build_worker_config defaults to
    # Hourglass.Client.default_namespace/0, which is the canonical
    # source. Passing it explicitly here would duplicate the lookup.
    #
    # Concurrency opts come from `:hourglass, Hourglass.Worker` config.
    # Unset = 0 → Rust DEFAULT_OUTSTANDING (10).
    concurrency_opts =
      :hourglass
      |> Application.get_env(Hourglass.Worker, [])
      |> Keyword.take([
        :max_outstanding_workflow_tasks,
        :max_outstanding_activities,
        :max_outstanding_local_activities
      ])

    opts = [task_queue: @default_task_queue] ++ concurrency_opts

    case WorkerSupervisor.start_worker(opts) do
      {:ok, _pid} -> :ignore
      {:error, {:already_started, _pid}} -> :ignore
      {:error, reason} -> {:error, reason}
    end
  end
end
